version: '3'
services:
  vehicles_db:
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=vehicles_db
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_vehicles_db.sql:/docker-entrypoint-initdb.d/init_vehicles_db.sql
volumes:
  db_data: