openapi: 3.1.0
info:
  title: Vehicle Registry API
  description: Api to manage the vehicle registry
  contact:
    email: aalonso@gmail.com
  version: 1.0.0
tags:
  - name: show_vehicles
    description: Check the vehicles of the database
  - name: add_vehicles
    description: Add new vehicles to the database
  - name: update_vehicles
    description: Update vehicles from the database
  - name: delete_vehicles
    description: Delete vehicles from the database
paths:
  /car_registry/show_all_vehicles:
    get:
      tags:
        - show_vehicles
      summary: Get the list of vehicles
      description: Returns the list of all vehicles
      operationId: showAllVehicles
      responses:
        '200':
          description: List found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '400':
          description: Bad request
        '404':
          description: Not vehicles found
        default:
          description: Unexpected error
        '500':
          description: Internal error
  /car_registry/show_vehicle_by_id:
    get:
      tags:
        - show_vehicles
      summary: Get vehicles
      description: Returns a vehicle by id
      operationId: showVehicleById
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: The id of the vehicle to retrieve
      responses:
        '200':
          description: Vehicle found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Bad request
        '404':
          description: Vehicle not found
        default:
          description: Unexpected error
        '500':
          description: Internal error
  /car_registry/show_all_brands:
    get:
      tags:
        - show_brands
      summary: Get the list of brands
      description: Returns the list of all brands
      operationId: showAllBrands
      responses:
        '200':
          description: List found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
        '400':
          description: Bad request
        '404':
          description: Not brands found
        default:
          description: Unexpected error
        '500':
          description: Internal error
  /car_registry/show_brand_by_id:
    get:
      tags:
        - show_brands
      summary: Get brand
      description: Returns a brand by id
      operationId: showBrandById
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: The id of the brand to retrieve
      responses:
        '200':
          description: Brand found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brand'
        '400':
          description: Bad request
        '404':
          description: Brand not found
        default:
          description: Unexpected error
        '500':
          description: Internal error
  /car_registry/add_vehicles:
    post:
      tags:
        - add_vehicles
      summary: Add vehicles
      description: Add a vehicle list
      operationId: addVehicles
      requestBody:
        description: List of vehicles to add
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Vehicle'
        required: true
      responses:
        '200':
          description: Vehicles added successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '400':
          description: Bad request
        default:
          description: Unexpected error
        '500':
          description: Internal error
  /car_registry/update_vehicle:
    put:
      tags:
        - update_vehicles
      summary: Update a vehicle
      description: Updates a vehicle
      operationId: updateVehicle
      requestBody:
        description: Vehicle data to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
        required: true
      responses:
        '200':
          description: Vehicle updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Bad request
        '404':
          description: Vehicle not found
        default:
          description: Unexpected error
        '500':
          description: Internal error
  /car_registry/delete_vehicle:
    delete:
      tags:
        - delete_vehicles
      summary: Delete a vehicle
      description: Deletes a vehicle by id
      operationId: deleteVehicle
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: The id of the vehicle to delete
      responses:
        '200':
          description: Vehicle deleted successfully
        '400':
          description: Bad request
        '404':
          description: Vehicle not found
        default:
          description: Unexpected error
        '500':
          description: Internal error
components:
  schemas:
    Vehicle:
      type: object
      properties:
        id:
          type: string
        brand:
          $ref: '#/components/schemas/Brand'
        model:
          type: string
        mileage:
          type: integer
        price:
          type: number
          format: double
        year:
          type: integer
        colour:
          type: string
        fuelType:
          type: string
        numDoors:
          type: integer
        description:
          type: string
    Brand:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        warranty:
          type: integer
        country:
          type: string